services:
  # Cơ sở dữ liệu PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bakers_postgres
    restart: always
    env_file:
      - ./be/.env.${APP_ENV:-development}
    environment:
      POSTGRES_USER: ${DB_USER:-bakers_admin}
      POSTGRES_PASSWORD: ${DB_PASS:-secretpassword}
      POSTGRES_DB: ${DB_NAME:-bakers_marketplace}
    networks:
      - bakers_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: bakers_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bakers.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - bakers_network
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Redis Cache
  redis:
    image: redis:8-alpine
    container_name: bakers_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend
  backend:
    container_name: bakers_backend
    build:
      context: ./be
      dockerfile: Dockerfile
      target: base # GIỮ LẠI DEV DEPENDENCIES
    restart: always
    networks:
      - bakers_network
    ports:
      - "4000:4000"
    env_file:
      - ./be/.env.${APP_ENV:-development}
    depends_on:
      - postgres
      - redis
    command: npm run dev:docker
    develop:
      watch:
        - action: sync+restart
          path: ./be/src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./be/package.json
        - action: rebuild
          path: ./be/package-lock.json

  #fe
  frontend:
    container_name: bakers_frontend
    build:
      context: ./fe
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file:
      - ./fe/.env.${APP_ENV:-development}
    networks:
      - bakers_network
    ports:
      - "3000:3000"
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./fe
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
            - .next/
            - package.json
            - package-lock.json
        - action: rebuild
          path: ./fe/package.json
        - action: rebuild
          path: ./fe/package-lock.json
volumes:
  pg_data:
  redis_data:

networks:
  bakers_network:
    driver: bridge
